[queue.quota.queue-max-size]
messages = 100000
size = 10737418240 # 10gb
enable = true

[queue.throttle.recipient-limit]
key = ["rcpt_domain"]
concurrency = 5
enable = true

[session.throttle.concurrency-by-remote-ip]
key = ["remote_ip"]
concurrency = 5
enable = true

[session.throttle.rate-by-sender]
key = ["sender_domain", "rcpt"]
rate = "25/1h"
enable = true
