#############################################
# SMTP Spam & Phishing filter configuration
#############################################

[spam.header]
add-spam = true
add-spam-result = true
is-spam = "X-Spam-Status: Yes"

[spam.autolearn]
enable = true
balance = 0.9

[spam.autolearn.ham]
replies = true
threshold = -0.5

[spam.autolearn.spam]
threshold = 6.0

[spam.threshold]
spam = 5.0
discard = 0
reject = 0

[spam.data]
directory = ""
lookup = ""

[sieve.trusted.scripts]
spam-filter = ["file://%{BASE_PATH}%/etc/spamfilter/scripts/config.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/prelude.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/from.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/recipient.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/subject.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/replyto.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/date.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/messageid.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/received.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/headers.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/bounce.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/html.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/mime.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/dmarc.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/ip.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/helo.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/replies_in.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/spamtrap.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/bayes_classify.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/url.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/rbl.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/pyzor.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/composites.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/scores.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/reputation.sieve",
               "file://%{BASE_PATH}%/etc/spamfilter/scripts/epilogue.sieve"]

track-replies = ["file://%{BASE_PATH}%/etc/spamfilter/scripts/config.sieve",
                 "file://%{BASE_PATH}%/etc/spamfilter/scripts/replies_out.sieve"]

greylist = ["file://%{BASE_PATH}%/etc/spamfilter/scripts/config.sieve",
            "file://%{BASE_PATH}%/etc/spamfilter/scripts/greylist.sieve"]
