[package]
name = "mail-server"
description = "Stalwart Mail Server"
authors = [ "Stalwart Labs Ltd. <hello@stalw.art>"]
repository = "https://github.com/stalwartlabs/jmap-server"
homepage = "https://stalw.art"
keywords = ["imap", "jmap", "smtp", "email", "mail", "server"]
categories = ["email"]
license = "AGPL-3.0-only"
version = "0.3.0"
edition = "2021"
resolver = "2"

[[bin]]
name = "stalwart-mail"
path = "crates/main/src/main.rs"

[dependencies]
store = { path = "crates/store" }
jmap = { path = "crates/jmap" }
jmap_proto = { path = "crates/jmap-proto" }
smtp = { path = "crates/smtp" }
utils = { path = "crates/utils" }
tests = { path = "tests" }

[workspace]
members = [
    "crates/jmap",
    "crates/jmap-proto",
    "crates/smtp",
    "crates/store",
    "crates/utils",
    "crates/maybe-async",
    "tests",
]
