#[package]
#name = "stalwart-jmap"
#description = "Stalwart JMAP Server"
#authors = [ "Stalwart Labs Ltd. <hello@stalw.art>"]
#repository = "https://github.com/stalwartlabs/jmap-server"
#homepage = "https://stalw.art/jmap"
#keywords = ["jmap", "email", "mail", "server"]
#categories = ["email"]
#license = "AGPL-3.0-only"
#version = "0.3.0"
#edition = "2021"
#resolver = "2"

#[lib]
#path = "crates/core/src/lib.rs"

[workspace]
members = [
    "crates/protocol",
    "crates/store",
    "crates/core",
    "tests",
]
