#############################################
# JMAP server listener configuration
#############################################

[server.listener."jmap"]
bind = ["[::]:8080"]
url = "https://__HOST__:8080"
protocol = "jmap"
