#############################################
# JMAP server listener configuration
#############################################

[server.listener."jmap"]
protocol = "jmap"
bind = ["[::]:443"]
url = "https://%{HOST}%"

#bind = ["[::]:8080"]
#url = "https://%{HOST}%:8080"
