#############################################
# JMAP Sieve interpreter configuration
#############################################

[sieve.jmap]
disable-capabilities = []
notification-uris = ["mailto"]
protected-headers = ["Original-Subject", "Original-From", "Received", "Auto-Submitted"]

[sieve.jmap.limits]
name-length = 512
max-scripts = 256
script-size = 102400
string-length = 4096
variable-name-length = 32
variable-size = 4096
nested-blocks = 15
nested-tests = 15
nested-foreverypart = 3
match-variables = 30
local-variables = 128
header-size = 1024
includes = 3
nested-includes = 3
cpu = 5000
redirects = 1
received-headers = 10
outgoing-messages = 3

[sieve.jmap.vacation]
default-subject = "Automated reply"
subject-prefix = "Auto: "

[sieve.jmap.default-expiry]
vacation = "30d"
duplicate = "7d"
