#############################################
# JMAP server store configuration
#############################################

[jmap.store]
data = "%{DEFAULT_STORE}%"
fts = "__FTS_STORE__"
blob = "__BLOB_STORE__"

[jmap.encryption]
enable = true
append = false

[jmap.fts]
default-language = "en"

[jmap.cluster]
node-id = 1
