#############################################
# JMAP server store configuration
#############################################

[jmap.store]
data = "rocksdb"
fts = "rocksdb"
blob = "rocksdb"

[jmap.encryption]
enable = true
append = false

[jmap.fts]
default-language = "en"

[jmap.cluster]
node-id = 1
