#############################################
# FoundationDB Store configuration
#############################################

[store."foundationdb"]
type = "foundationdb"
#cluster-file = "/etc/foundationdb/fdb.cluster"
disable = true

#[store."foundationdb".transaction]
#timeout = "5s"
#retry-limit = 10
#max-retry-delay = "1s"

#[store."foundationdb".ids]
#machine = "stalwart"
#data-center = "my-datacenter"

[store."foundationdb".purge]
frequency = "0 3 *"
