#############################################
# Redis Lookup Store configuration
#############################################

[store."redis"]
type = "redis"
redis-type = "single"
urls = ["redis://127.0.0.1"] 
user = "my_username"
password = "secretpassword"
timeout = "10s"
#read-from-replicas = false
disable = true

#[store."redis".retry]
#total = 3
#max-wait = "1s"
#min-wait = "500ms"
