#############################################
# Cache configuration
#############################################

[cache]
capacity = 512
shard = 32

[cache.session]
ttl  = "1h"

[cache.account]
size = 2048

[cache.mailbox]
size = 2048

[cache.thread]
size = 2048

[cache.bayes]
capacity = 8192

[cache.bayes.ttl]
positive = "1h"
negative = "1h"

[cache.resolver]
txt = 2048
mx = 1024
ipv4 = 1024
ipv6 = 1024
ptr = 1024
tlsa = 1024
mta-sts = 1024
