#############################################
# Server configuration
#############################################

[server]
hostname = "%{HOST}%"
max-connections = 8192

#[server.proxy]
#trusted-networks = ["127.0.0.0/8", "::1", "10.0.0.0/8"]

[authentication]
fail2ban = "100/1d"
rate-limit = "10/1m"

[server.run-as]
user = "stalwart-mail"
group = "stalwart-mail"

[server.socket]
nodelay = true
reuse-addr = true
#reuse-port = true
backlog = 1024
#ttl = 3600
#send-buffer-size = 65535
#recv-buffer-size = 65535
#linger = 1
#tos = 1

[global]
#thread-pool = 8

[server.http]
#headers = ["Access-Control-Allow-Origin: *", 
#           "Access-Control-Allow-Methods: POST, GET, PATCH, PUT, DELETE, HEAD, OPTIONS",
#           "Access-Control-Allow-Headers: Authorization, Content-Type, Accept, X-Requested-With"]
