[package]
name = "store"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
utils = { path = "../utils" }
nlp = { path = "../nlp" }
rocksdb = { version = "0.20.1", optional = true }
foundationdb = { version = "0.8.0", features = ["embedded-fdb-include"], optional = true }
rusqlite = { version = "0.29.0", features = ["bundled"], optional = true }
rust-s3 = { version = "0.33.0", default-features = false, features = ["tokio-rustls-tls"] }
tokio = { version = "1.23", features = ["sync", "fs", "io-util"] }
r2d2 = { version = "0.8.10", optional = true }
futures = { version = "0.3", optional = true }
rand = "0.8.5"
roaring = "0.10.1"
rayon = { version = "1.5.1", optional = true }
serde = { version = "1.0", features = ["derive"]}
ahash = { version = "0.8.0", features = ["serde"] }
lazy_static = "1.4"
xxhash-rust = { version = "0.8.5", features = ["xxh3"] }
farmhash = "1.1.5"
parking_lot = "0.12.1"
lru-cache = { version = "0.1.2", optional = true }
num_cpus = { version = "1.15.0", optional = true }
blake3 = "1.3.3"
tracing = "0.1"
async-trait = "0.1.68"
lz4_flex = { version = "0.11" }
deadpool-postgres = "0.11.0"
tokio-postgres = "0.7.10"
tokio-rustls = { version = "0.24.0"}
rustls = "0.21.0"
ring = "0.17"
mysql_async = { version = "*", default-features = false, features = ["default-rustls"] }

[dev-dependencies]
tokio = { version = "1.23", features = ["full"] }

[features]
rocks = ["rocksdb", "rayon"]
sqlite = ["rusqlite", "rayon", "r2d2", "num_cpus", "lru-cache"]
foundation = ["foundationdb", "futures"]
backend = []
test_mode = []


