#############################################
# Internal Directory configuration
#############################################

[directory."internal"]
type = "internal"
store = "%{DEFAULT_STORE}%"
disable = true

[directory."internal".options]
catch-all = true
#catch-all = [ { if = "matches('(.+)@(.+)$', address)", then = "'info@' + $2" },
#              { else = false } ]
subaddressing = true
#subaddressing = [ { if = "matches('^([^.]+)\.([^.]+)@(.+)$', address)", then = "$2 + '@' + $3" }, 
#                  { else = false } ]

[directory."internal".cache]
entries = 500
ttl = {positive = '1h', negative = '10m'}
