#############################################
# SQL Directory configuration
#############################################

[directory."sql"]
type = "sql"
store = "__SQL_STORE__"
disable = true

[directory."sql".options]
catch-all = true
#catch-all = [ { if = "matches('(.+)@(.+)$', address)", then = "'info@' + $2" },
#              { else = false } ]
subaddressing = true
#subaddressing = [ { if = "matches('^([^.]+)\\.([^.]+)@(.+)$', address)", then = "$2 + '@' + $3" }, 
#                  { else = false } ]

[directory."sql".cache]
entries = 500
ttl = {positive = '1h', negative = '10m'}

[directory."sql".columns]
class = "type"
secret = "secret"
description = "description"
quota = "quota"
